### ISSUE TITLE
Exception while trying to stop function.

### ISSUE THREAD

**Issue by bablosoft** [CheshireCaat/bas-remote-node#4]
```javascript
    const options = {
        scriptName: 'TestRemoteControl'
    };

    const client = new BasRemoteClient(options);

    await client.start();

    var promise1 = client.runFunction('GoogleSearch', {Query: 'cats'});
    
    promise1.Stop(); //stop also doesn't work

    await promise1;


    await client.close();
```

Following code will throw exception 

```
UnhandledPromiseRejectionWarning: TypeError: promise1.Stop is not a function
```

Also, can you rename ```Stop``` method to ```stop```

**Comment by bablosoft** [comment]
Works ok in 1.0.9
